name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Ruby 2.6.6
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ruby-2.6.6 # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Build and test with RSpec
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rspec
